include:
  - template: Security/SAST.gitlab-ci.yml

image: docker:latest

services:
  - docker:dind

stages:
    - build 
    - test    

heappe_build:
    stage: build
    before_script:
        - docker --version
    only:
        - master
        - develop
    tags:
        - Docker
        - HEAppE
    script:
        - docker build -t "${HEAPPE_CONTAINER_NAME}" -f ./RestApi/Dockerfile .

sshagent_build:
    stage: build
    before_script:
        - docker --version
    only:
        - master
        - develop
    tags:
        - Docker
        - HEAppE
    script:
        - docker build -t ${SSHAGENT_CONTAINER_NAME} -f ./SshAgent/Dockerfile .
