receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:${env:OTEL_HOST_GRPC_PORT}

processors:
  # Protect Collector from memory exhaustion
  memory_limiter:
    check_interval: 1s
    limit_mib: 1024
    spike_limit_mib: 256
  # Batch telemetry to reduce write overhead
  batch:
    timeout: 5s                 # sends a batch after timeout value
    send_batch_size: 1000       # target size of the batch (could be larger in some circumstances)
    send_batch_max_size: 1000   # hard limit
  # Keep all errors and high latency traces, sample success traces at sampling_percentage
  tail_sampling:
    decision_wait: 20s    # maximum expected trace duration
    num_traces: 1000      # Number of traces to keep in memory
    policies: # processed in order, with OR logic
      [
        {
          name: status-policy,
          type: status_code,
          status_code: {status_codes: [ERROR]}
        },
        {
          name: latency-policy,
          type: latency,
          latency: {threshold_ms: 100}
        },
        { 
          name: probabilistic-policy, 
          type: probabilistic,
          probabilistic: {sampling_percentage: 10}
        }
      ]

exporters:
  file/traces:
    path: /var/log/otel/traces.json
    rotation:
      max_megabytes: 512  # max file size
      max_backups: 10     # max files to keep
      max_days: 7         # number of days of history
    compression: zstd
  otlp/jaeger:
    endpoint: jaeger:4317 # The address of the Jaeger gRPC endpoint
    tls:
      insecure: true # TODO: use TLS in production

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, tail_sampling, batch]
      exporters: [file/traces, otlp/jaeger]