{{- if .Values.mssql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heappe.mssql.fullname" . }}
  labels:
    {{- include "heappe.labels" . | nindent 4 }}
    {{- include "heappe.mssql.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  sa-password: {{ .Values.mssql.saPassword | b64enc | quote }}
{{- end }}
