{{- if .Values.telemetry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heappe.otelcollector.fullname" . }}
  labels:
    {{- include "heappe.labels" . | nindent 4 }}
    {{- include "heappe.otelcollector.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "heappe.otelcollector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "heappe.labels" . | nindent 8 }}
        {{- include "heappe.otelcollector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: otel-collector
          image: "{{ if .Values.global.imageRegistry }}{{ .Values.global.imageRegistry }}/{{ end }}{{ .Values.telemetry.otelCollector.image.repository }}:{{ .Values.telemetry.otelCollector.image.tag }}"
          imagePullPolicy: {{ .Values.telemetry.otelCollector.image.pullPolicy }}
          args: ["--config", "/etc/otel/config.yaml"]
          ports:
            - name: grpc
              containerPort: {{ .Values.telemetry.otelCollector.grpcPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/otel/config.yaml
              subPath: otel-config.yaml
          resources:
            {{- toYaml .Values.telemetry.otelCollector.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "heappe.otelcollector.fullname" . }}-config
{{- end }}
