{{- if and .Values.vault.enabled (not .Values.vault.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "heappe.vault.fullname" . }}
  labels:
    {{- include "heappe.labels" . | nindent 4 }}
    {{- include "heappe.vault.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.vault.server.port }}
      targetPort: {{ .Values.vault.server.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "heappe.vault.selectorLabels" . | nindent 4 }}
{{- end }}
