apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heappe.fullname" . }}-connectionstrings
type: Opaque
data:
  MiddlewareContext: {{ include "heappe.mssql.connectionString" . | b64enc | quote }}