{{- if .Values.vault.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "heappe.vaultagent.fullname" . }}
  labels:
    {{- include "heappe.labels" . | nindent 4 }}
    {{- include "heappe.vaultagent.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.vault.agent.port }}
      targetPort: {{ .Values.vault.agent.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "heappe.vaultagent.selectorLabels" . | nindent 4 }}
{{- end }}
